package com.hometail.web.dto;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Data Transfer Object representing an adoption request in the system.
 * This class is used to transfer adoption request data between different layers of the application.
 * 
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class AdoptionRequestDTO implements java.io.Serializable {
    private static final long serialVersionUID = 1L;

    /** Unique identifier for the adoption request (generated by the back-end) */
    private Long id;
    
    /** ID of the animal being requested for adoption */
    private Long animalId;
    
    /** ID of the user who created the adoption request */
    private Long requesterId;
    
    /** Additional notes or message from the requester */
    private String note;
    
    /** 
     * Current status of the adoption request
     * Possible values: PENDING, APPROVED, REJECTED
     */
    private String status;
    
    /** Timestamp when the request was created (ISO-8601 format) */
    private String createdAt;
    
    /** Timestamp when the request was decided (ISO-8601 format) */
    private String decisionAt;
    
    /** Full name of the person making the adoption request */
    private String requesterName;
    
    /** Email address of the requester */
    private String requesterEmail;
    
    /** Contact phone number of the requester */
    private String requesterPhone;
    
    /** Name of the animal being requested */
    private String animalName;
    
    /** Category of the animal (e.g., Dog, Cat) */
    private String animalCategory;
    
    /** Name of the current owner of the animal */
    private String ownerName;
    
    /** ID of the current owner of the animal */
    private Long animalOwnerId;
    
    /** Detailed information about the animal */
    private AnimalDTO animal;

}
